// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Travel.DrivenAdapters.SqlServer;

#nullable disable

namespace Atencion.Migrations
{
    [DbContext(typeof(AtencionDbContext))]
    partial class AtencionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Atencion.Domain.Model.Seguimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodClasificacionNutricional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodLugarAtencion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodManejoActual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodTratamiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodUbicacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesManejo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesUbicacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoVital")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAtencion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaDefuncion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int");

                    b.Property<string>("OtroTratamiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PesoKg")
                        .HasColumnType("int");

                    b.Property<int>("TallaCm")
                        .HasColumnType("int");

                    b.Property<int>("TotalSobreFTLC")
                        .HasColumnType("int");

                    b.Property<string>("UbicacionDefuncion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Seguimiento");
                });

            modelBuilder.Entity("Travel.Domain.Model.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodAsegurador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodMpioResidencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NroIdentificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoIdentificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persona");
                });
#pragma warning restore 612, 618
        }
    }
}
